name: flutter_native_pdf_view_example
description: Demonstrates how to use the native_pdf_view plugin.
publish_to: 'none'

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  path_provider: ^0.4.1
  photo_view: ^0.1.3
  native_pdf_view:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/sample.pdf
