name: epub_view
description: Flutter widget for view EPUB documents on all platforms. Based on dart-epub package.
version: 0.1.0
author: Serge Shkurko <sergeshkurko@outlook.com>
homepage: https://github.com/rbcprolabs/packages.flutter/tree/master/packages/epub_view

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  epub: ^2.0.0
  flutter_html: ^0.11.0
  flutter_widgets: ^0.1.7+1

dev_dependencies:
  flutter_test:
    sdk: flutter

