name: native_pdf_view
description: Flutter plugin to render PDF files on Web, MacOS, Android and iOS.
version: 3.5.0
homepage: https://github.com/rbcprolabs/packages.flutter/tree/master/packages/native_pdf_view

environment:
  sdk: '>=2.7.0 <3.0.0'
  flutter: '>=1.17.0 <2.0.0'

dependencies:
  flutter:
    sdk: flutter
  extended_image: ^0.7.3+1
  synchronized: ^2.2.0
  device_info: ^0.4.2+4
  native_pdf_renderer: 
    path: ../native_pdf_renderer

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.9.0
