name: native_pdf_renderer
description: Flutter plugin to render PDF pages as images on both Android and iOS devices.
version: 2.1.1
homepage: https://github.com/rbcprolabs/packages.flutter/tree/master/packages/native_pdf_renderer

environment:
  sdk: '>=2.7.0 <3.0.0'
  flutter: '>=1.17.0 <2.0.0'

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.1.8
  extension: ^0.1.1
  synchronized: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.9.0

flutter:
  plugin:
    platforms:
      android:
        package: io.scer.pdf.renderer
        pluginClass: NativePDFRendererPlugin
      ios:
        pluginClass: NativePDFRendererPlugin
