name: explorer
description: Universal explorer UI for navigate files, ftp, etc
version: 1.1.0
homepage: https://github.com/rbcprolabs/packages.flutter/tree/master/packages/explorer

environment:
  sdk: '>=2.8.0 <3.0.0'
  flutter: '>=1.22.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter     
  intl: ^0.17.0  
  flutter_breadcrumb: ^0.1.2
  auto_animated: ^3.0.0
  sliver_tools: ^0.2.0-nullsafety
  path: ^1.8.0
  meta: ^1.3.0
  io: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.11.5
  intl_translation: ^0.17.10+1

dependency_overrides:
  build_runner: ^1.11.5
  analyzer: ^1.1.0 
  args: ^2.0.0
  intl: ^0.17.0 
  io: ^1.0.0

scripts:
  i18n: flutter pub run easy_localization:generate -s assets/locales -f keys -O lib/src/i18n -o locale_keys.g.dart
