name: explorer
description: Universal explorer UI for navigate files, ftp, etc
version: 1.0.0
homepage: https://github.com/rbcprolabs/packages.flutter/tree/master/packages/explorer

environment:
  sdk: '>=2.8.0 <3.0.0'
  flutter: '>=1.17.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_breadcrumb: ^0.1.2
  auto_animated: ^3.0.0
  sliver_tools: ^0.2.0-nullsafety
  path: ^1.8.0
  meta: ^1.3.0
  io: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

