name: native_pdf_view_example
description: Demonstrates how to use the native_pdf_view plugin.
version: 1.0.0
publish_to: 'none'

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  performance: ^0.1.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  native_pdf_view:
    path: ../

flutter:
  uses-material-design: true

  assets:
    - assets/sample.pdf
    - assets/dummy.pdf
    - assets/hello.pdf
