name: auto_animated
description: Widgets starting auto play animation when mounted. It is already possible to animate the list and icons.
version: 2.0.0
author: Serge Shkurko <sergeshkurko@outlook.com>
homepage: https://github.com/rbcprolabs/packages.flutter/tree/master/packages/auto_animated

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_widgets: ^0.1.7+1

dev_dependencies:
  flutter_test:
    sdk: flutter
