name: auto_animated
description: Widgets starting auto play animation when mounted. It is already possible to animate the list and icons.
version: 2.0.2
homepage: https://github.com/rbcprolabs/packages.flutter/tree/master/packages/auto_animated

environment:
  sdk: '>=2.5.2 <3.0.0'
  flutter: '>=1.9.1 <2.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_widgets: ^0.1.11

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.8.0+1
